---
- name: install dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - at
      - bc
      - cmake
      - ffmpeg
      - gmic
      - gnuradio
      - gr-osmosdr
      - imagemagick
      - jq
      - libgles-dev
      - libegl-dev
      - libatlas-base-dev
      - libgfortran5
      - libjpeg9
      - libjpeg9-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libsox-fmt-mp3
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libxft-dev
      - libxft2
      - predict
      - wkhtmltopdf
      - python3-pip
      - python-setuptools
      - socat
      - sox
      - sqlite3
      - certbot

- name: Installing WXtoImg
  become: yes
  apt:
    deb: "{{ noaa_home }}/software/wxtoimg-{{ system_architecture }}-2.11.2-beta.deb"
    state: present
    update_cache: no

#- name: Installing MeteorDemod
#  become: yes
#  apt:
#    deb: "https://github.com/Digitelektro/MeteorDemod/releases/download/2.5.6-beta/meteordemod_2.5.6_{{ system_architecture }}.deb"
#    state: present
#    update_cache: no

- name: Installing SatDump
  become: yes
  apt:
    deb: "{{ noaa_home }}/software/satdump_1.1.0_{{ system_architecture }}.deb"
    state: present
    update_cache: no

- name: Check if libbrcmGLESV2.50 link exists
  stat:
    path: /usr/lib/libbrcmGLESV2.50
  register: libGLESV2_link
  ignore_errors: yes

- name: Create symbolic link for libGLESV2.so
  command: ln -s /usr/lib/arm-linux-gnueabihf/libGLESV2.so /usr/lib/libbrcmGLESV2.50
  become: yes
  when: not libGLESV2_link.stat.exists

- name: Check if libbrcmEGL.so link exists
  stat:
    path: /usr/lib/libbrcmEGL.so
  register: libEGL_link
  ignore_errors: yes

- name: Create symbolic link for libEGL.so
  command: ln -s /usr/lib/arm-linux-gnueabihf/libEGL.so /usr/lib/libbrcmEGL.so
  become: yes
  when: not libEGL_link.stat.exists

- name: Installing AnyDesk remote desktop
  become: yes
  apt:
    deb: "{{ noaa_home }}/software/anydesk_6.3.0-1_{{ system_architecture }}.deb"
    state: present
    update_cache: no
...
